spring:
  application:
    name: SGC-Admin
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

management:
  security:
    enabled: false #关掉安全认证
  context-path: /management #actuator的访问路径　


druid:
  pool:
    initialSize: 10
    maxActive: 100
    minIdle: 10


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/domain/mapper/*Mapper.xml
  typeAliasesPackage: com.sgc.domain.mapper
  global-config:
    id-type: 3
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    
    
#    regCenter:
#  serverList: localhost:6181
#  namespace: elastic-job-lite-springboot
#  
#simpleJob:
#  cron: 0/5 * * * * ?
#  shardingTotalCount: 3
#  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
#  
#dataflowJob:
#  cron: 0/5 * * * * ?
#  shardingTotalCount: 3
#  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

#Geth
web3j:
  url: 139.199.203.145
  port: 9891